fuse: readdir: add missing variables
Fixes error:

../fs/fuse/readdir.c:357:15: error: use of undeclared identifier 'page'
  357 |         ap->pages = &page;
      |                      ^~~~
../fs/fuse/readdir.c:358:15: error: use of undeclared identifier 'desc'
  358 |         ap->descs = &desc;
      |                      ^~~~
../fs/fuse/readdir.c:380:37: error: use of undeclared identifier 'page'
  380 |                         res = parse_dirfile(page_address(page), res, file,
      |                                                          ^~~~
3 errors generated.

Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>