fs: Fix ST_LOG no-op build warnings
Make disabled ST_LOG fallbacks use no_printk() instead of expanding to
nothing so log-only arguments still get consumed and filesystem builds
do not trip unused-variable warnings.

../fs/namespace.c:166:9: error: unused variable 'bd_dev' [-Werror,-Wunused-variable]
  166 |                 dev_t bd_dev = bdev ? bdev->bd_dev : 0;
      |                       ^~~~~~
../fs/namespace.c:160:6: error: unused variable 'mnt_flags' [-Werror,-Wunused-variable]
  160 |         int mnt_flags = mnt->mnt.mnt_flags;
      |             ^~~~~~~~~

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
(cherry picked from commit 7f23399e6fea0624d5b1ab9741b1651b61d27aab)
Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>