BACKPORT: seccomp: add filter_count field for KernelSU • KernelSU requires struct seccomp to have atomic_t filter_count , but this field is missing on NON-GKI kernels.
Adding the field fixes build errors such as:

 error: no member named 'filter_count' in 'struct seccomp'

Reference: tiann/KernelSU#2708
Actual Commit: GrapheneOS-Archive/kernel_common-5.10@c818c03

Co-authored-by: Kees Cook <keescook@chromium.org>
Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>