block: genhd: Fix ST_LOG KOBJ_ADD build issues
Use disk->major and disk->first_minor directly in the KOBJ_ADD ST_LOG
calls so block builds cleanly when ST_LOG is compiled through no_printk().

../block/genhd.c:676:42: error: use of undeclared identifier 'major'; did you mean 'imajor'?
  676 |         ST_LOG("<%s> KOBJ_ADD %d:%d", __func__, major, first_minor);
      |                                                 ^~~~~
      |                                                 imajor
../block/genhd.c:29:43: note: expanded from macro 'ST_LOG'
   29 | #define ST_LOG(fmt, ...) no_printk(fmt, ##__VA_ARGS__)
      |                                           ^~~~~~~~~~~
../include/linux/printk.h:140:17: note: expanded from macro 'no_printk'
  140 |                 printk(fmt, ##__VA_ARGS__);             \
      |                               ^~~~~~~~~~~
../include/linux/fs.h:931:24: note: 'imajor' declared here
  931 | static inline unsigned imajor(const struct inode *inode)
      |                        ^
../block/genhd.c:676:49: error: use of undeclared identifier 'first_minor'
  676 |         ST_LOG("<%s> KOBJ_ADD %d:%d", __func__, major, first_minor);
      |                                                        ^~~~~~~~~~~
../block/genhd.c:682:43: error: use of undeclared identifier 'major'; did you mean 'imajor'?
  682 |                 ST_LOG("<%s> KOBJ_ADD %d:%d", __func__, major,
      |                                                         ^~~~~
      |                                                         imajor
../block/genhd.c:29:43: note: expanded from macro 'ST_LOG'
   29 | #define ST_LOG(fmt, ...) no_printk(fmt, ##__VA_ARGS__)
      |                                           ^~~~~~~~~~~
../include/linux/printk.h:140:17: note: expanded from macro 'no_printk'
  140 |                 printk(fmt, ##__VA_ARGS__);             \
      |                               ^~~~~~~~~~~
../include/linux/fs.h:931:24: note: 'imajor' declared here
  931 | static inline unsigned imajor(const struct inode *inode)
      |                        ^
../block/genhd.c:683:27: error: use of undeclared identifier 'first_minor'
  683 |                                         first_minor + part->partno);
      |                                         ^~~~~~~~~~~
4 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
(cherry picked from commit d7edf28328c1649d7d2e677b67e43cb00cc5d033)
Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>